import { SUPPORTED_DENO_VERSION } from './deno-runtime.js';

/** Immutable actions/checkout v6 release commit. */
const ACTIONS_CHECKOUT_SHA = 'd23441a48e516b6c34aea4fa41551a30e30af803';

/** Immutable denoland/setup-deno v2.0.5 release commit. */
const SETUP_DENO_SHA = '22d081ff2d3a40755e97629de92e3bcbfa7cf2ed';

/**
 * Generate the conservative Custom Function GitHub Actions workflow.
 *
 * @param options - Workflow paths and pinned CLI version
 * @returns Workflow YAML
 */
export function generateGithubActionsWorkflow(options: {
  /** Exact released CLI version. */
  cliVersion: string;
  /** Target directory relative to the repository root. */
  targetDirectory: string;
  /** Manifest directory where generated source, payload, and Deno files live. */
  contentDirectory?: string;
  /** Manifest path relative to the repository root. */
  manifestPath: string;
  /** Additional manifest-referenced files that should trigger validation. */
  watchedPaths?: readonly string[];
}): string {
  const { cliVersion, targetDirectory, manifestPath } = options;
  const contentDirectory = options.contentDirectory ?? targetDirectory;
  const pathPrefix = contentDirectory === '.' ? '' : `${contentDirectory.replace(/\/+$/u, '')}/`;
  const watchedPaths = [
    `${pathPrefix}functions/**`,
    `${pathPrefix}test-payloads/**`,
    manifestPath,
    `${pathPrefix}deno.json*`,
    ...(options.watchedPaths ?? []),
  ].filter((path, index, paths) => paths.indexOf(path) === index);
  const pathFilters = watchedPaths.map((path) => `      - ${JSON.stringify(path)}`).join('\n');
  return `# Generated by transcend custom-functions init.
name: Transcend Custom Functions

on:
  pull_request:
    paths:
${pathFilters}
  push:
    paths:
${pathFilters}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${ACTIONS_CHECKOUT_SHA} # v6
      - uses: denoland/setup-deno@${SETUP_DENO_SHA} # v2.0.5
        with:
          deno-version: ${SUPPORTED_DENO_VERSION}
      - name: Install the Transcend CLI
        run: npm install --global @transcend-io/cli@${cliVersion}
      - name: Validate Custom Functions
        env:
          CUSTOM_FUNCTION_DIRECTORY: ${JSON.stringify(targetDirectory)}
          CUSTOM_FUNCTION_MANIFEST: ${JSON.stringify(manifestPath)}
        run: >-
          transcend custom-functions check "$CUSTOM_FUNCTION_DIRECTORY"
          --manifest="$CUSTOM_FUNCTION_MANIFEST"
          --noInteractive
          --json
`;
}
