import { createHash } from 'node:crypto';

import { RECOMMENDED_DENO_VERSION } from './deno-runtime.js';

/** Immutable actions/checkout v6 release commit. */
const ACTIONS_CHECKOUT_SHA = 'd23441a48e516b6c34aea4fa41551a30e30af803';

/** Immutable denoland/setup-deno v2.0.5 release commit. */
const SETUP_DENO_SHA = '22d081ff2d3a40755e97629de92e3bcbfa7cf2ed';

/**
 * Escape a repository path before embedding intentional GitHub glob syntax.
 *
 * @param path - Literal repository-relative path
 * @returns Path with GitHub glob metacharacters escaped
 */
function escapeGithubPath(path: string): string {
  return path.replace(/([!*?[\]\\])/gu, '\\$1');
}

/**
 * Check whether a generated workflow still matches its ownership digest.
 *
 * @param contents - Existing workflow
 * @returns Whether automatic replacement is safe
 */
export function isUnmodifiedCustomFunctionWorkflow(contents: string): boolean {
  const marker = contents.match(
    /# managed-by: @transcend-io\/cli; content-sha256: ([a-f0-9]{64})\s*$/u,
  );
  if (!marker || marker.index === undefined) {
    return false;
  }
  const body = contents.slice(0, marker.index).trimEnd();
  return createHash('sha256').update(body).digest('hex') === marker[1];
}

/**
 * Generate the conservative Custom Function GitHub Actions workflow.
 *
 * @param options - Workflow paths and pinned CLI version
 * @returns Workflow YAML
 */
export function generateGithubActionsWorkflow(options: {
  /** Exact released CLI version. */
  cliVersion: string;
  /** Target directory relative to the repository root. */
  targetDirectory: string;
  /** Manifest directory where generated source, payload, and Deno files live. */
  contentDirectory?: string;
  /** Manifest path relative to the repository root. */
  manifestPath: string;
  /** Additional manifest-referenced files that should trigger validation. */
  watchedPaths?: readonly string[];
}): string {
  const { cliVersion, targetDirectory, manifestPath } = options;
  const contentDirectory = options.contentDirectory ?? targetDirectory;
  const pathPrefix =
    contentDirectory === '.' ? '' : `${escapeGithubPath(contentDirectory.replace(/\/+$/u, ''))}/`;
  const watchedPaths = [
    `${pathPrefix}functions/**`,
    `${pathPrefix}test-payloads/**`,
    escapeGithubPath(manifestPath),
    `${pathPrefix}deno.json*`,
    ...(options.watchedPaths ?? []).map(escapeGithubPath),
  ].filter((path, index, paths) => paths.indexOf(path) === index);
  const pathFilters = watchedPaths.map((path) => `      - ${JSON.stringify(path)}`).join('\n');
  const body = `# Generated by transcend custom-functions init.
name: Transcend Custom Functions

on:
  pull_request:
    paths:
${pathFilters}
  push:
    paths:
${pathFilters}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${ACTIONS_CHECKOUT_SHA} # v6
      - uses: denoland/setup-deno@${SETUP_DENO_SHA} # v2.0.5
        with:
          deno-version: ${RECOMMENDED_DENO_VERSION}
      - name: Install the Transcend CLI
        run: npm install --global @transcend-io/cli@${cliVersion}
      - name: Validate Custom Functions
        env:
          CUSTOM_FUNCTION_DIRECTORY: ${JSON.stringify(targetDirectory)}
          CUSTOM_FUNCTION_MANIFEST: ${JSON.stringify(manifestPath)}
        run: >-
          transcend custom-functions check "$CUSTOM_FUNCTION_DIRECTORY"
          --manifest="$CUSTOM_FUNCTION_MANIFEST"
          --noInteractive
          --json
`;
  const digest = createHash('sha256').update(body.trimEnd()).digest('hex');
  return `${body.trimEnd()}\n\n# managed-by: @transcend-io/cli; content-sha256: ${digest}\n`;
}
