/**
 * GraphQL Code Generator configuration for the Transcend MCP server packages.
 *
 * This config drives two outputs per GraphQL-backed MCP server:
 *   1. `src/__generated__/` — `client-preset` artifacts producing a typed
 *      `graphql()` template tag and `TypedDocumentNode`s for every embedded
 *      operation. The MCP server's `graphql.ts` files use this tag, and
 *      `TranscendGraphQLBase.makeRequest` infers `TResult`/`TVariables` from
 *      the document.
 *   2. `src/__generated__/zod-inputs.ts` — Zod schemas mirroring every GraphQL
 *      `input` type referenced from the server's operations, generated by
 *      `graphql-codegen-typescript-validation-schema`. MCP tool schemas wrap
 *      these via the `withDescriptions` helper to enforce AI-friendly copy.
 *
 * The schema is read from the committed `schema.graphql` at the repo root.
 * That file is refreshed on a schedule by `.github/workflows/refresh-graphql-schema.yml`,
 * which keeps PR CI hermetic (no network round-trip during builds).
 */
import type { CodegenConfig } from '@graphql-codegen/cli';

const SCHEMA_PATH = './schema.graphql';

/**
 * GraphQL-backed MCP servers. Each entry corresponds to a package directory
 * `packages/mcp/mcp-server-${name}` containing a `src/graphql.ts` file with
 * embedded operations. The `mcp-server-base`, `mcp-server-consent`, and
 * `mcp-server-preferences` packages are intentionally excluded:
 *   - base has no GraphQL operations of its own.
 *   - consent/preferences hit REST endpoints, not GraphQL.
 */
const SERVERS = ['admin', 'assessment', 'discovery', 'dsr', 'inventory', 'workflows'] as const;

const config: CodegenConfig = {
  schema: SCHEMA_PATH,
  // Tolerate servers that haven't migrated to the typed `graphql()` tag yet.
  // Once every operation in a package is on the typed tag, the
  // `description-audit` test guarantees coverage; this flag keeps codegen
  // green while migrations land incrementally.
  ignoreNoDocuments: true,
  generates: Object.fromEntries(
    SERVERS.flatMap((server) => {
      const pkgRoot = `packages/mcp/mcp-server-${server}/src`;
      const documents = [`${pkgRoot}/**/*.ts`, `!${pkgRoot}/__generated__/**`];
      return [
        [
          `${pkgRoot}/__generated__/`,
          {
            documents,
            preset: 'client',
            config: {
              useTypeImports: true,
              skipTypename: false,
              // `verbatimModuleSyntax` + `moduleResolution: NodeNext` require
              // explicit `.js` extensions on relative imports inside emitted
              // ESM. Disable the legacy CJS shim so the preset emits clean
              // ESM-style relative imports with `.js` extensions.
              emitLegacyCommonJSImports: false,
              importExtension: '.js',
              // Transcend's GraphQL API exposes a custom `Date` scalar (ISO-8601
              // strings, not the JS `Date` instance). Map it to a native string
              // so the response/variables types stay JSON-friendly.
              scalars: {
                Date: 'string',
              },
            },
            presetConfig: {
              fragmentMasking: false,
            },
          },
        ],
        [
          `${pkgRoot}/__generated__/zod-inputs.ts`,
          {
            documents,
            plugins: ['typescript', 'graphql-codegen-typescript-validation-schema'],
            config: {
              schema: 'zod',
              useTypeImports: true,
              withObjectType: false,
              scalarSchemas: {
                Date: 'z.string()',
              },
              scalars: {
                Date: 'string',
              },
              onlyOperationTypes: true,
            },
          },
        ],
      ] as const;
    }),
  ),
};

export default config;
