min_version = "2026.3.17"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
lockfile = true

[hooks]
postinstall = "npx corepack enable"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]

[tools]
shellcheck = "0.11.0"

[tasks.bootstrap]
description = "Set up workspace"
run = '''
pnpm install
pnpm build
pnpm quality
'''
