export * from './cocoaPods.js';
export * from './gradle.js';
export * from './javascriptPackageJson.js';
export * from './pythonRequirementsTxt.js';
export * from './gemfile.js';
export * from './pubspec.js';
export * from './composerJson.js';
export * from './swift.js';
export * from './kotlin.js';
