// Header text at the top of all generated files
export const HEADER = '// Auto-generated by Terrazzo — do not edit manually\n';

// Suffix for token file names
export const TOKEN_FILE_SUFFIX = '.tokens.json';

// Filename substring that identifies dark-mode override files
export const DARK_MODE_SUFFIX = '-dark';
