import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createGenerator } from 'ts-json-schema-generator';
import ts from 'typescript';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const contractPath = resolve(packageRoot, 'src/contract.ts');
const tsconfigPath = resolve(packageRoot, 'tsconfig.json');
const checkOnly = process.argv.includes('--check');

const schemaDefinitions = [
  {
    type: 'CustomFunction.MaestroTestPayload',
    filename: 'general-payload.json',
    title: 'General Custom Function payload',
    id: 'file:///general-custom-function-payload.schema.json',
    constantName: 'GENERAL_CUSTOM_FUNCTION_PAYLOAD_SCHEMA',
  },
  {
    type: 'CustomFunction.DataPointTestPayload',
    filename: 'dsr-datapoint-payload.json',
    title: 'Data subject request (DSR) datapoint Custom Function payload',
    id: 'file:///dsr-datapoint-custom-function-payload.schema.json',
    constantName: 'DSR_DATAPOINT_CUSTOM_FUNCTION_PAYLOAD_SCHEMA',
  },
  {
    type: 'CustomFunction.EnricherTestPayload',
    filename: 'dsr-request-enricher-payload.json',
    title: 'Data subject request (DSR) request enricher Custom Function payload',
    id: 'file:///dsr-request-enricher-custom-function-payload.schema.json',
    constantName: 'DSR_REQUEST_ENRICHER_CUSTOM_FUNCTION_PAYLOAD_SCHEMA',
  },
];

const generatedFiles = new Map();

for (const definition of schemaDefinitions) {
  const schema = createGenerator({
    path: contractPath,
    tsconfig: tsconfigPath,
    type: definition.type,
    expose: 'export',
    topRef: false,
    jsDoc: 'extended',
    additionalProperties: false,
    sortProps: true,
    strictTuples: true,
    skipTypeCheck: false,
  }).createSchema(definition.type);

  const normalizedSchema = {
    ...schema,
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: definition.id,
    title: definition.title,
  };

  generatedFiles.set(
    resolve(packageRoot, 'src/__generated__/schemas', definition.filename),
    `${JSON.stringify(normalizedSchema, null, 2)}\n`,
  );
  definition.schema = normalizedSchema;
}

const declarationResult = ts.transpileDeclaration(readFileSync(contractPath, 'utf8'), {
  compilerOptions: {
    exactOptionalPropertyTypes: true,
    lib: ['ES2022', 'DOM', 'DOM.Iterable'],
    module: ts.ModuleKind.ESNext,
    strict: true,
    target: ts.ScriptTarget.ESNext,
  },
  fileName: contractPath,
  reportDiagnostics: true,
});

if (declarationResult.diagnostics?.length) {
  const diagnostics = ts.formatDiagnosticsWithColorAndContext(declarationResult.diagnostics, {
    getCanonicalFileName: (filename) => filename,
    getCurrentDirectory: () => packageRoot,
    getNewLine: () => '\n',
  });
  throw new Error(`Failed to emit Custom Function declarations:\n${diagnostics}`);
}

const declarationFile = ts.createSourceFile(
  'contract.d.ts',
  declarationResult.outputText,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TS,
);
const namespaceDeclaration = declarationFile.statements.find(
  (statement) =>
    ts.isModuleDeclaration(statement) &&
    ts.isIdentifier(statement.name) &&
    statement.name.text === 'CustomFunction',
);

if (!namespaceDeclaration) {
  throw new Error('Could not find the emitted CustomFunction namespace');
}

const namespaceText = ts
  .createPrinter({ newLine: ts.NewLineKind.LineFeed })
  .printNode(ts.EmitHint.Unspecified, namespaceDeclaration, declarationFile)
  .replace('export declare namespace CustomFunction', 'declare namespace CustomFunction')
  .replace(
    'interface SDK {',
    `class SDK {
        private customerIngressBaseUrl;
        private customerIngressAuth;
        private transcendNonce;
        constructor(customerIngressBaseUrl: string, customerIngressAuth: string, transcendNonce: string);`,
  )
  .replace('environment: Environment;', 'environment: EnvironmentGlobals.Environment;');

generatedFiles.set(
  // Keep the `.txt` suffix so webpack emits this declaration as a fetchable
  // asset instead of consuming it as a compile-time TypeScript declaration.
  resolve(packageRoot, 'src/__generated__/monaco/lib.custom-function.d.ts.txt'),
  `// Generated from src/contract.ts. Do not edit directly.
type CommonPayloadProperties = CustomFunction.CommonPayloadProperties;
type CommonsExtraProperties = CustomFunction.CommonExtras;
declare namespace EnvironmentGlobals {
    interface Environment {}
}
${namespaceText}
`,
);

const schemaSource = `// Generated by scripts/generateArtifacts.mjs. Do not edit directly.
import type { CustomFunctionJsonSchema } from '../schema.js';

${schemaDefinitions
  .map(
    ({ constantName, schema }) =>
      `export const ${constantName} = ${JSON.stringify(
        schema,
        null,
        2,
      )} as const satisfies CustomFunctionJsonSchema;`,
  )
  .join('\n\n')}
`;

generatedFiles.set(resolve(packageRoot, 'src/__generated__/payloadSchemas.ts'), schemaSource);

const staleFiles = [];
for (const [filename, expectedContents] of generatedFiles) {
  if (checkOnly) {
    if (!existsSync(filename) || readFileSync(filename, 'utf8') !== expectedContents) {
      staleFiles.push(filename);
    }
    continue;
  }

  mkdirSync(dirname(filename), { recursive: true });
  writeFileSync(filename, expectedContents);
}

if (staleFiles.length > 0) {
  throw new Error(
    `Generated Custom Function artifacts are stale:\n${staleFiles
      .map((filename) => `- ${filename}`)
      .join('\n')}\nRun \`pnpm generate\` in packages/custom-function-types.`,
  );
}
