import {
  createListResult,
  defineTool,
  OffsetPaginationSchema,
  z,
  type ToolClients,
} from '@transcend-io/mcp-server-base';
import { AssessmentFormTemplateSource } from '@transcend-io/privacy-types';

import type { AssessmentsMixin } from '../graphql.js';
import { describeNoMatches } from '../helpers/describeNoMatches.js';

/**
 * Three-query test. An agent holding only the tool list should land here, and
 * only here, for each of these:
 *
 * 1. "Which of our templates came over from OneTrust?"
 *    Reaches `sources: ['IMPORT']`. The enum value says IMPORT and the caller
 *    says OneTrust, so the description has to carry the vendor's name or the
 *    query finds nothing.
 *
 * 2. "What templates has Daniel built?"
 *    Reaches `creatorIds`, after resolving the name through `admin_list_users`,
 *    which the field description points at.
 *
 * 3. "Who last edited the vendor risk template?"
 *    Reaches `text` plus `includeDetails`, since the compact row deliberately
 *    omits the people.
 */

export const ListTemplatesSchema = OffsetPaginationSchema.extend({
  text: z.string().optional().describe('Free-text match on the template title and description'),
  ids: z.array(z.string()).optional().describe('Specific template IDs to fetch'),
  statuses: z
    .array(z.enum(['DRAFT', 'PUBLISHED']))
    .optional()
    .describe('Publication statuses to include. Omit for both.'),
  sources: z
    .array(z.nativeEnum(AssessmentFormTemplateSource))
    .optional()
    .describe(
      'How the template was made: MANUAL (someone built it), DATA_INVENTORY (generated by ' +
        'assessments kicked off from the data inventory), IMPORT (came in with a OneTrust ' +
        'import). Omit for all three.',
    ),
  creatorIds: z
    .array(z.string())
    .optional()
    .describe(
      'Transcend user IDs who created the template. Resolve names with `admin_list_users`. ' +
        'Templates that predate this being recorded have no creator and match no one.',
    ),
  lastEditorIds: z
    .array(z.string())
    .optional()
    .describe(
      'Transcend user IDs who last edited it. Resolve names with `admin_list_users`. ' +
        'A template nobody has edited matches no one.',
    ),
  includeDetails: z
    .boolean()
    .optional()
    .default(false)
    .describe(
      'Also return who created and who last edited each template, where either was recorded',
    ),
});
export type ListTemplatesInput = z.infer<typeof ListTemplatesSchema>;

export function createAssessmentsListTemplatesTool(clients: ToolClients) {
  const graphql = clients.graphql as AssessmentsMixin;
  return defineTool({
    name: 'assessments_list_templates',
    description:
      'Find blank assessment templates, the starting points new assessments are built from. ' +
      'Narrow with `text`, with `sources` for how a template was made — by hand, generated ' +
      'from the data inventory, or imported from OneTrust — and with `creatorIds` or ' +
      '`lastEditorIds` for who built it or last changed it. Use the returned `id` as ' +
      '`templateId` for `assessments_export_template` to read the questions, or for ' +
      '`assessments_create`. Each row has id, title, description, status, source, isArchived, ' +
      'createdAt and updatedAt; `includeDetails` adds the two people. No date filter or sort ' +
      'exists, so rank by createdAt yourself when asked which are new.',
    category: 'Assessments',
    readOnly: true,
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
    zodSchema: ListTemplatesSchema,
    handler: async ({
      limit,
      offset,
      text,
      ids,
      statuses,
      sources,
      creatorIds,
      lastEditorIds,
      includeDetails,
    }) => {
      const result = await graphql.listAssessmentTemplates({
        first: limit,
        offset,
        includeDetails,
        filterBy: {
          ...(text && { text }),
          ...(ids?.length && { ids }),
          ...(statuses?.length && { statuses }),
          ...(sources?.length && { sources }),
          ...(creatorIds?.length && { creatorIds }),
          ...(lastEditorIds?.length && { lastEditorIds }),
        },
      });

      const appliedFilters = Object.entries({
        text,
        ids: ids?.length,
        statuses: statuses?.length,
        sources: sources?.length,
        creatorIds: creatorIds?.length,
        lastEditorIds: lastEditorIds?.length,
      })
        .filter(([, value]) => Boolean(value))
        .map(([name]) => name);

      return createListResult(result.nodes, {
        totalCount: result.totalCount,
        hasNextPage: result.pageInfo?.hasNextPage,
        ...(result.totalCount === 0 && {
          paginationNote: describeNoMatches('templates', appliedFilters),
        }),
      });
    },
  });
}
