/** Immutable actions/checkout v6 release commit. */
const ACTIONS_CHECKOUT_SHA = 'd23441a48e516b6c34aea4fa41551a30e30af803';

/** Immutable denoland/setup-deno v2.0.5 release commit. */
const SETUP_DENO_SHA = '22d081ff2d3a40755e97629de92e3bcbfa7cf2ed';

/** Deno version used by generated validation workflows. */
export const GENERATED_DENO_VERSION = '2.5.6';

/**
 * Generate the conservative Custom Function GitHub Actions workflow.
 *
 * @param options - Workflow paths and pinned CLI version
 * @returns Workflow YAML
 */
export function generateGithubActionsWorkflow(options: {
  /** Exact released CLI version. */
  cliVersion: string;
  /** Target directory relative to the repository root. */
  targetDirectory: string;
  /** Manifest path relative to the repository root. */
  manifestPath: string;
}): string {
  const { cliVersion, targetDirectory, manifestPath } = options;
  const pathPrefix = targetDirectory === '.' ? '' : `${targetDirectory.replace(/\/+$/u, '')}/`;
  return `# Generated by transcend custom-functions init.
# Run the first deployment manually with --updateManifest and commit assigned IDs
# before enabling TRANSCEND_CUSTOM_FUNCTIONS_DEPLOY in repository variables.
name: Transcend Custom Functions

on:
  pull_request:
    paths:
      - '${pathPrefix}functions/**'
      - '${pathPrefix}test-payloads/**'
      - '${manifestPath}'
      - '${pathPrefix}deno.json*'
  push:
    paths:
      - '${pathPrefix}functions/**'
      - '${pathPrefix}test-payloads/**'
      - '${manifestPath}'
      - '${pathPrefix}deno.json*'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${ACTIONS_CHECKOUT_SHA} # v6
      - uses: denoland/setup-deno@${SETUP_DENO_SHA} # v2.0.5
        with:
          deno-version: ${GENERATED_DENO_VERSION}
      - name: Install the Transcend CLI
        run: npm install --global @transcend-io/cli@${cliVersion}
      - name: Validate Custom Functions
        env:
          CUSTOM_FUNCTION_DIRECTORY: '${targetDirectory}'
          CUSTOM_FUNCTION_MANIFEST: '${manifestPath}'
        run: >-
          transcend custom-functions check "$CUSTOM_FUNCTION_DIRECTORY"
          --manifest="$CUSTOM_FUNCTION_MANIFEST"
          --noInteractive
      - name: Deploy from the trusted default branch
        if: >-
          github.event_name == 'push' &&
          github.ref_name == github.event.repository.default_branch &&
          vars.TRANSCEND_CUSTOM_FUNCTIONS_DEPLOY == 'true'
        env:
          CUSTOM_FUNCTION_MANIFEST: '${manifestPath}'
          CUSTOM_FUNCTION_VARIABLES: \${{ secrets.CUSTOM_FUNCTION_VARIABLES }}
          SOMBRA_INTERNAL_KEY: \${{ secrets.SOMBRA_INTERNAL_KEY }}
          TRANSCEND_API_KEY: \${{ secrets.TRANSCEND_API_KEY }}
        run: |
          test -n "$TRANSCEND_API_KEY" || {
            echo "TRANSCEND_API_KEY is required when deployment is enabled." >&2
            exit 1
          }
          args=(
            custom-functions push
            "--file=$CUSTOM_FUNCTION_MANIFEST"
            "--auth=$TRANSCEND_API_KEY"
          )
          test -z "$SOMBRA_INTERNAL_KEY" ||
            args+=("--sombraAuth=$SOMBRA_INTERNAL_KEY")
          test -z "$CUSTOM_FUNCTION_VARIABLES" ||
            args+=("--variables=$CUSTOM_FUNCTION_VARIABLES")
          transcend "\${args[@]}"
`;
}
