/**
 * Refresh the committed `schema.graphql` at the repo root by introspecting a
 * live Transcend GraphQL endpoint.
 *
 * Run modes:
 *   - Local:    `pnpm graphql:refresh-schema` (reads `secret.env` for the API
 *               key + URL override, defaults to staging).
 *   - CI cron:  `.github/workflows/refresh-graphql-schema.yml` invokes this
 *               with `TRANSCEND_API_KEY` + `TRANSCEND_API_URL` in env.
 *
 * The script is idempotent: it prints the SDL alphabetically-sorted via
 * `printSchema` so byte-stable diffs surface only meaningful schema changes.
 *
 * Why we commit the schema:
 *   - Hermetic CI for unrelated PRs (no flaky network on every run).
 *   - Local-first dev: contributors don't need staging credentials to typecheck.
 *   - A single PR shows exactly which schema changes are landing.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  buildClientSchema,
  getIntrospectionQuery,
  type IntrospectionQuery,
  printSchema,
} from 'graphql';

const DEFAULT_STAGING_URL = 'https://api.staging.transcen.dental';

interface IntrospectionResponse {
  data?: IntrospectionQuery;
  errors?: Array<{ message: string }>;
}

function loadSecretEnv(): void {
  const path = resolve(process.cwd(), 'secret.env');
  let contents: string;
  try {
    contents = readFileSync(path, 'utf8');
  } catch {
    return;
  }
  for (const rawLine of contents.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    // Only fill in from secret.env when the variable is fully unset; an
    // explicit empty string in the parent env is honored as "do not auth".
    if (process.env[key] === undefined && value) {
      process.env[key] = value;
    }
  }
}

async function main(): Promise<void> {
  loadSecretEnv();

  const apiKey = process.env.TRANSCEND_API_KEY;
  const baseUrl = (process.env.TRANSCEND_API_URL ?? DEFAULT_STAGING_URL).replace(/\/$/, '');
  const url = `${baseUrl}/graphql`;
  // eslint-disable-next-line no-console
  console.error(`Introspecting ${url}…`);

  // Transcend's GraphQL endpoint allows introspection without auth, which lets
  // CI refresh the schema with no secret. We still send the API key when
  // present so a misconfigured staging that *does* require auth still works.
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      ...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}),
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify({ query: getIntrospectionQuery({ descriptions: true }) }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Introspection HTTP ${response.status}: ${text}`);
  }

  const result = (await response.json()) as IntrospectionResponse;
  if (result.errors?.length) {
    throw new Error(`Introspection errors: ${result.errors.map((e) => e.message).join('; ')}`);
  }
  if (!result.data) {
    throw new Error('Introspection returned no data');
  }

  const schema = buildClientSchema(result.data);
  const sdl = printSchema(schema);
  const banner = `# Generated by scripts/refresh-graphql-schema.ts
# Source: ${url}
# DO NOT EDIT BY HAND. Run \`pnpm graphql:refresh-schema\` to regenerate.
`;
  const outputPath = resolve(process.cwd(), 'schema.graphql');
  writeFileSync(outputPath, `${banner}\n${sdl}\n`);

  // eslint-disable-next-line no-console
  console.error(`Wrote ${outputPath} (${sdl.length} bytes).`);
}

main().catch((err: unknown) => {
  // eslint-disable-next-line no-console
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
