import { posix } from 'node:path';

import { POLICY_STARTER_OPA_VERSION } from './policy-scaffold-templates.js';

/** Regal version pinned by generated policy validation. */
export const POLICY_STARTER_REGAL_VERSION = '0.42.0';

/** Repository-relative generated workflow path. */
export const POLICY_CI_WORKFLOW_PATH = '.github/workflows/transcend-policy.yml';

/** Immutable actions/checkout v6 release commit. */
export const ACTIONS_CHECKOUT_SHA = 'd23441a48e516b6c34aea4fa41551a30e30af803';

/** Immutable open-policy-agent/setup-opa v2.4.0 release commit. */
export const SETUP_OPA_SHA = 'b2b258e089860efaadaaf71bf6e3aecb4a3eeff1';

/** Immutable open-policy-agent/setup-regal v2.0.0 release commit. */
export const SETUP_REGAL_SHA = '761188c3b435761fa254beca508a44875619648f';

/**
 * Prefix a path below the repository-relative policy target.
 *
 * @param targetDirectory - POSIX repository-relative target
 * @param child - POSIX target-relative path or pattern
 * @returns Repository-relative path or pattern
 */
function targetPath(targetDirectory: string, child: string): string {
  return targetDirectory === '.' ? child : posix.join(targetDirectory, child);
}

/**
 * Generate credential-free, validation-only Policy Engine CI.
 *
 * @param options - Repository paths and exact CLI release
 * @returns Complete GitHub Actions workflow YAML
 */
export function generatePolicyGithubActionsWorkflow(options: {
  /** Exact released Transcend CLI version. */
  cliVersion: string;
  /** Policy directory relative to the repository root. */
  targetDirectory: string;
}): string {
  const watchedPaths = [
    targetPath(options.targetDirectory, '**/*.rego'),
    targetPath(options.targetDirectory, '**/*.json'),
    targetPath(options.targetDirectory, '**/*.yaml'),
    targetPath(options.targetDirectory, '**/*.yml'),
    targetPath(options.targetDirectory, '.regal/config.yaml'),
    targetPath(options.targetDirectory, '.regal.yaml'),
    POLICY_CI_WORKFLOW_PATH,
  ];
  const pathFilters = watchedPaths.map((path) => `      - ${JSON.stringify(path)}`).join('\n');

  return `# Generated by transcend policy init.
name: Transcend Policy

on:
  pull_request:
    paths:
${pathFilters}
  push:
    paths:
${pathFilters}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${ACTIONS_CHECKOUT_SHA} # v6
      - name: Set up OPA
        uses: open-policy-agent/setup-opa@${SETUP_OPA_SHA} # v2.4.0
        with:
          version: ${JSON.stringify(POLICY_STARTER_OPA_VERSION)}
      - name: Set up Regal
        uses: open-policy-agent/setup-regal@${SETUP_REGAL_SHA} # v2.0.0
        with:
          version: ${JSON.stringify(POLICY_STARTER_REGAL_VERSION)}
      - name: Install the Transcend CLI
        run: npm install --global @transcend-io/cli@${options.cliVersion}
      - name: Validate Policy Engine project
        env:
          POLICY_DIRECTORY: ${JSON.stringify(options.targetDirectory)}
        run: >-
          transcend policy lint
          --dir "$POLICY_DIRECTORY"
          --noInteractive
          --json
`;
}
