name: Preview Release

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'

concurrency:
  group: preview-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      pull-requests: write
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Bootstrap
        uses: ./.github/commands/bootstrap

      - name: Build
        run: pnpm build

      - name: Check package quality
        run: pnpm quality

      - name: Publish PR previews
        shell: bash
        run: | #shell
          pnpm exec pkg-pr-new publish \
            --pnpm \
            --packageManager=pnpm,yarn \
            --commentWithSha \
            --previewVersion \
            './packages/*' \
            './packages/mcp'
